name: python-linter-pipeline

on: push

jobs:
  python-lint:
    name: Python lint code base
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Python Linter
        with:
            source: "src"
            mypy-options: "--ignore-missing-imports --show-error-codes"
            pylint-options: "--rcfile=setup.cfg"
            isort-options: "-w 100"
            django: true
